### ISSUE TITLE
meuse.grid$part.a wrongly rendered

### ISSUE THREAD

**Issue by edzer** [environmentalinformatics-marburg/mapview#1]
Tim, great work!

I noticed that in one of the raster maps part_a was rendered wrongly, in the example

mapView(meuse_rst)

however,

> unique(meuse.grid$part.a)
[1] 1 0

so we shouldn't see more than two colours.

**Comment by tim-salabim** [comment]
Edzer,
thanks for pointing this out.

This is due to the fact that meuse_rst[[1]] (ehich is meuse.grid$part.a) is rendered as a numeric layer, not a factor layer.
If you do

part_a <- ratify(meuse_rst[[1]]
mapView(part_a)

you will see that the legend gets rendered correctly (showing only two colors).
The map itself is still rendered incorrectly, which is due to the fact that leaflet projects the layer using projectRasterForLeaflet() which is defined as 

raster::projectRaster(x, raster::projectExtent(x, crs = sp::CRS(epsg3857)))

hence using method = "bilinear" (the standard) and subsequently the layer becomes numeric again.

I intend to address this by avoiding the call to projectRasterForLeaflet() alltogether but ensuring the Raster* objects get projected correctly depending on their type before passing them to leaflet::addRasterImage().

Best
Tim

**Comment by tim-salabim** [comment]
This is now resolved.
Included a function to reproject RasterLayers that checks whether layer is factorial and if it is, then uses method 'nearest neighbor' rather than the default 'bilinear'.

Tim

**Comment by edzer** [comment]
Well-done - thanks!
