### ISSUE TITLE
Feature request: Synchronizing two maps 

### ISSUE THREAD

**Issue by chamaoskurumi** [environmentalinformatics-marburg/mapview#19]
JS leaflet allows [two maps to be synchronized][1]. See an example of synchronized leaflet maps [here][2]. 

**I would like to implement synchronized leaflet maps in `R` and more specifially in `Rmarkdown/knitr`.** 

Preferably, the maps should shown next to each other horizontally (just like in the [example][2]).

I posted this on [StackOverflow][3] as well.

  [1]: https://github.com/turban/Leaflet.Sync
  [2]: http://blog.thematicmapping.org/2013/06/creating-synchronized-view-of-two-maps.html
  [3]:  https://stackoverflow.com/questions/36373842/synchronizing-two-leaflet-maps-in-r-rmarkdown

**Comment by timelyportfolio** [comment]
As stated in the StackOverflow, this would be a very helpful function to include in `mapview`.  I think we can adapt the answer.  Instead of using `tags$head` it is better practice to use `htmltools::attachDependency` or add the `Leaflet.sync` dependency to the `htmlwidget`.  Here is one [example](https://github.com/timelyportfolio/navr/blob/master/R/add_navr.R) and [another](https://github.com/rstudio/leaflet/blob/52c792d9db313df60a5741f8678d7c05e307cdfe/R/controls.R#L19) of the latter approach.

**Comment by timelyportfolio** [comment]
Reference @tim-salabim https://github.com/environmentalinformatics-marburg/mapview/commit/74a84e76e771d7cdaebb8fd539856527ac8b7381#diff-4604f089e357e45e73f2f7ed83595c1a

**Comment by tim-salabim** [comment]
@timelyportfolio thanks for the golden tip. Your first example link was a heureka moment for me :+1: 
This lead me to rethink the whole functionality and I've now deleted syncView and replaced it with latticeView. As it is now, we can create any number of panels and arrange them by setting the number of columns. Furthermore, we can sync any combination of them via `sync = list(c(1, 2), c(3, 4))` for example to sync panels 1 and 2 and panels 2 and 4. Additionlly, `sync = "none"` will not sync any panels and `sync = "all"` will sync all panels. Though I have not tested it explicitly, this should also work for maps created with `leaflet`. I also found that [Leaflet.Sync](https://github.com/turban/Leaflet.Sync) has two additional options which can also be set.

See `?latticeView` for a number of examples highlighting the use.

Let me know what you think. 
Also, a thing that is completely beyond my JavaScript capabilities is how to control the layout more flexibly by also specifying `nrow` in order to adjust the height of the divs. But this boils down to me not even understanding why I can set `width=100%` in js but not `height=100%`. Mybe you can enlighten me?

**Comment by timelyportfolio** [comment]
@tim-salabim, quite a first draft!  Very well done.  I did a line comment on `cursor` instead of `curser`.

I like how you add the layout capabilities.  I wonder though if layout is outside of the scope of `mapview` with all the tools on the HTML/CSS/JS side or like `flexdashboard` on the `R` side.  Perhaps, your approach is great for R users not well-versed in HTML/CSS/JS, but we might need a way to override or turn off the layout engine for those using these other tools.

In terms of `width=100%`, that is to make it sort of responsive.  We can't set `height=100%` due to a "bug" in which the map won't appear without either an explicit `height` or `width`.

**Comment by timelyportfolio** [comment]
@tim-salabim, thinking through this a little more, perhaps you could leave the very helpful `latticeView` and generalize/abstract out the `sync` piece.  I know this makes things much more complicated, but say something like.  Of course, this could come in a future version, since I think the `latticeView` is so nice.

```
sync(mapview1,mapview2)
```

**Comment by tim-salabim** [comment]
@timelyportfolio this is a good suggestion! I will think about how to implement that nicely and flexibly.

**Comment by timelyportfolio** [comment]
@tim-salabim, I am trying to think of a way to avoid assigning an `elementId` to the `leaflet` maps, but I don't think there is a workaround.  In the `sync` function, you could check for `leaflet1$elementId`, and then if `NULL`, then use a method similar to `htmlwidget` [line](https://github.com/ramnathv/htmlwidgets/blob/master/R/htmlwidgets.R#L165) to generate a "random" unique identifier (`elementId`) that will allow you to know on the `JavaScript` side which leaflet maps you want to sync.  Once you have that `elementId`, you can use that in your sync string.

**Comment by timelyportfolio** [comment]
Hopefully, I can have a go at this later today.  If not today, will be next week though.

**Comment by timelyportfolio** [comment]
Instead of `tagList(...)` with `onRenderStaticComplete(...)`, I think we will need to use `onRender` for each leaflet map and add the code that `onRenderStaticComplete` uses in these [lines](https://github.com/ramnathv/htmlwidgets/blob/master/R/utils.R#L205-L211).

```
onRender(
  leafletmap,
  paste0(
    "HTMLWidgets.addPostRenderHandler(function() {",
    syncstring,
    "});",
    collapse="\n"
  )
}
```

**Comment by tim-salabim** [comment]
There is no rush. As I said, we are aiming at second week of June (end thereof) for the release... Even if it stays as it is right now, I think it will be quite usable

**Comment by timelyportfolio** [comment]
@tim-salabim, would you ever expect a `leaflet` separate from `latticeView` or two `latticeView()` on a single page, such as

```
tagList(
  latticeView(m1,m2),
  tags$h3('another separate lattice view'),
  latticeView(m3,m4)
)
```

If so, then we will need to change to the hash approach in `onRenderStaticComplete` that I mentioned above. Even if not the hash approach will be more robust.

**Comment by tim-salabim** [comment]
If I understand you correctly, the answer is no. As you mentioned earlier that the nitty gritty layout is not for mapview but should be achieved with shiny or flexdashborad or ... In mapview we are mainly concerned with providing useful functionality for quick data glances during the workflow (i.e. how do my 2 classifications compare).
But then, it is always hard to know what people may find useful... Therefore I am a fan of keeping things flexible for future changes/additions

**Comment by timelyportfolio** [comment]
@tim-salabim great to know. Thanks.  I'll work up a pull for the hash approach which should be more robust regardless of the answer.

**Comment by timelyportfolio** [comment]
don't know where exactly to put this, but @tim-salabim, the `develop` branch is truly special and quite spectacular.  I'd like to see if maybe we can convince @walkerke to help review.

**Comment by tim-salabim** [comment]
@timelyportfolio I like the sarcasm :-) But let's not get ahead of ourselves... If I could get your email I would like to inaugurate you in some of our future plans regarding mapview. You'll find my email at http://www.uni-marburg.de/fb19/fachgebiete/umweltinformatik/appelhanst/index.html

**Comment by timelyportfolio** [comment]
@tim-salabim, no sarcasm intended.  `mapview` is amazing, and you have done really well.  I'll email.

**Comment by walkerke** [comment]
I've not yet used this package but it appears very useful!  I'd be happy to take a look.

**Comment by tim-salabim** [comment]
Wie now have functions lattice view() and sync() to view multiple maps on one page and optionally sync them. So I'm closing this issue
