### ISSUE TITLE
spatialpoints with only a single feature 

### ISSUE THREAD

**Issue by dschneiderch** [environmentalinformatics-marburg/mapview#3]
mapView() fails if you try to plot a spatialpointsDF with 1 feature because the min and max are the same when checking the extents.

**Comment by tim-salabim** [comment]
can you please provide a reproducible example.

when I do:

data(meuse)
tst <- meuse[1, ]
coordinates(tst) <- ~x+y
proj4string(tst) <- CRS("+init=epsg:28992")

mapView(tst)

it does not fail.
The only thing I see is that the pop-up is rendered incorrectly.
Or is that what you mean?

**Comment by dschneiderch** [comment]
Sorry to be imprecise.
It fails if you try to add it to a raster.
this fails:
data(meuse)
tst <- meuse[1,]
coordinates(tst) <- ~x+y
proj4string(tst) <- CRS("+init=epsg:28992")

data(meuse.grid)
gridded(meuse.grid)=~+x+y
proj4string(meuse.grid)=CRS("+init=epsg:28992")
meuse.raster=raster(meuse.grid)

mapView(meuse.raster)+mapView(tst)

it works fine if tst has at least 2 rows (although it zooms into the extent
of tst rather than staying at the raster extent)

Dominik Schneider
o 303.735.6296 | c 518.956.3978

**Comment by tim-salabim** [comment]
This is now fixed in version 0.5.2 on branch 'develop' and should work as expected. Please check and close this issue if you are satisfied with the new behaviour.

The '+-methods' now check whether the added layer has only one feature and if so do not set the extent explicitly. 

Zooming into the extent of the feature layer that is added last is a choice I delibarately made as it seems natural to zoom to the layer that gets added last.

Cheers
Tim

**Comment by dschneiderch** [comment]
Sorry, can you explain how to install the develop branch?

Dominik Schneider
o 303.735.6296 | c 518.956.3978

**Comment by tim-salabim** [comment]
install and load library(devtools) and then run

install_github("environmentalinformatics-marburg/mapview", ref = "develop")

**Comment by dschneiderch** [comment]
Ok, looks good.  Awesome work on the package. It was sorely needed.

Dominik Schneider
o 303.735.6296 | c 518.956.3978

**Comment by tim-salabim** [comment]
Thanks :-)
