### ISSUE TITLE
mapview doesn't like multi-Lines in SpatialLinesDataFrame

### ISSUE THREAD

**Issue by ateucher** [environmentalinformatics-marburg/mapview#31]
```r
library(sp)
library(mapview)
l1 = cbind(c(1,2,3),c(3,2,2))
l1a = cbind(l1[,1]+.05,l1[,2]+.05)
l2 = cbind(c(1,2,3),c(1,1.5,1))
Sl1 = Line(l1)
Sl1a = Line(l1a)
Sl2 = Line(l2)
S1 = Lines(list(Sl1, Sl1a), ID="a") # Make a multi-Line
S2 = Lines(list(Sl2), ID="b")
Sl = SpatialLines(list(S1,S2))
proj4string(Sl) <- CRS("+init=epsg:4326")
SlDF <- SpatialLinesDataFrame(Sl, data.frame(d = c("a", "b"), row.names = c("a", "b")))
mapview(SlDF)

#> Error in sp::Lines(list(coords), ID) : Single ID required
```

**Comment by ateucher** [comment]
And thank you for the great package!

**Comment by fdetsch** [comment]
Thanks for reporting this issue. Using the latest 'develop' version of **mapview**, the above code works on my machine now. The problem was obviously related to the 1-column dataset that - since each line from a multi-line segment is processed separately - was passed on to `sp::SpatialLinesDataFrame` (argument 'data') as `factor` rather than `data.frame`. Anyway, can you please test it?

**Comment by ateucher** [comment]
Works great for me - thanks!
