### ISSUE TITLE
Error in map$dependencies : $ operator not defined for this S4 class

### ISSUE THREAD

**Issue by adrfantini** [environmentalinformatics-marburg/mapview#43]
When using the latest `leaflet` from github together with mapView, I get this error:

    mapview() %>% addMeasure()
    Error in map$dependencies : $ operator not defined for this S4 class

While using `leaflet` directly works:

    leaflet() %>% addMeasure()

This is true not only for `addMeasure()`, but also for other add-in plugins to github leaflet , such as `addGraticule()`, `addMiniMap()` etc.

At one point it actually worked, but then I updated both packages and it seems to be broken now.

EDIT: It seems to work if I issue:

    mapview() %>% addMouseCoordinates() %>% addMiniMap()

However, the mouse coords are not shown if using `mapView` from Cran, only with `mapView` from github.

**Comment by timelyportfolio** [comment]
I could be wrong, but I think you need to do

```
mapview()@map %>% add*
```

Also, `leaflet` is undergoing very rapid development, so CRAN/Github will be touch and go until there is some stability.

**Comment by adrfantini** [comment]
Why is this tho? I thought `mapview()` acted just as `leaflet()` did. And
why does the last command work, by just adding `addMouseCoordinates()`.

I mean, I can see why, but does it make sense? It's not very intuitive.

2016-10-28 16:54 GMT+02:00 timelyportfolio <notifications@github.com>:

**Comment by tim-salabim** [comment]
@adrfantini I agree that this is not intuitive but it was a deliberate choice related to the scope of **mapview**. 

Some background: **mapview** is specifically designed to be used for spatial analysis (workflow). The aim is to provide simple and quick methods to view spatial data classes interactively (sp and raster at the moment, sf soon to be supported). Thus providing a more powerful tool for visual checking of intermediate results, basically providing a more powerful `(sp)plot` method. 
Given that it is based on **leaflet** (for the most part anyway) this has some implications. The coordinate reference system used by **leaflet** is so-called `web-mercator` but people work with spatial data in all sorts of projections. In order to provide a quick visualisation with **mapview** we need to re-project on-the-fly. However, web-mercator is defined only for data between 85.051129 degrees north and south which means that there may be instances where we loose features that are located beyond those limits. Furthermore, users can define their own `proj4strings` which sometimes results in semi-correct projections where e.g. a different ellipsoid is used, but not defined in the crs information which will ultimately lead to wrong placement on the map. Therefore, we opted for returning both the generated map as well as the data as displayed on the map to enable the user to track differences between his original input and what they see on the map. Thus, **mapview** returns an object with 2 slots, `@object` (a list of all data layers shown on the map) and `@map` (the actual **leaflet** map object). Note, this is only true for the `mapview` calls, all provided functions such as `addMouseCoordinates`, `addHomeButton` etc. do not, cannot and should not return any data, because they are decoration for the map, nothing else. 

The reason why you can call `addMouseCoodinates()` directly on a **mapview** object is that this function is provided by **mapview** where we can handle the extraction of the `@map` slot of the object internally. All functions provided by **leaflet** expect a valid **leaflet** map object, i.e. the `@map` part of the **mapview** object. 

As @timelyportfolio pointed out, both **leaflet** and **mapview** are currently undergoing major development, so things may be a little shaky when working with a combination of stable and development versions of the packages. Working with both CRAN versions should work fine, and working with both github versions should work at least better than working with a mix of the two. 
The specific reason for `addMouseCoordinates` from the CRAN version of **mapview** failing to work with the github version of **leaflet** is that the latter was upgraded to work with a newer version of the underlying leafletjs JavaScript library which the way we implemented `addMouseCoordinates`. It is fixed on github, but until the next CRAN release you simply need to make sure that you are using compatible versions of the two packages. 

I hope this helps clarify your questions.

**Comment by adrfantini** [comment]
Hi,
this indeed clarifies my doubts, thank you a lot!
This is very clear, thank you for taking your time to reply and also for
creating this awesome package.
You can close this if you please.

2016-10-28 18:32 GMT+02:00 tim-salabim <notifications@github.com>:
