### ISSUE TITLE
mapshot could not determine mime type

### ISSUE THREAD

**Issue by brry** [environmentalinformatics-marburg/mapview#69]
When saving a map created from an ESRI shapefile, I run into an error.
Things still seeem to work fine, so I'm not too bothered, but in case it might be worth looking into, here's the error:

```R
SHP <- sf::st_read("shapefile.shp")
MAP <- mapview::mapview(SHP)
mapshot(MAP, "map.html")

pandoc.exe: Could not determine mime type for `map_files/SHP-1/data_large_SHP072c13.geojson'
Error: pandoc document conversion failed with error 1
In addition: Warning message:
running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS 
C:\Users\boessenkool\Dropbox\MaisanbauVerschnitt16\map.html --from markdown --output 
C:\Users\boessenkool\Dropbox\MaisanbauVerschnitt16\map.html --self-contained --template 
C:\Users\BOESSE~1\AppData\Local\Temp\RtmpKUOZzf\file178046f759f0.html' had status 1 



traceback()

5: pandoc_convert(input = input, from = "markdown", output = output, 
       options = c("--self-contained", "--template", template))
4: pandoc_self_contained_html(file, file)
3: (function (widget, file, selfcontained = TRUE, libdir = NULL, 
       background = "white", knitrOptions = list()) 
[...]
2: do.call(htmlwidgets::saveWidget, append(list(x), sw_ls[sw_args]))
1: mapshot(MAP, "map.html")
```

**Comment by tim-salabim** [comment]
Seems like you are trying to save a rather large map. Please try `mapshot(MAP, "map.html", selfcontained = FALSE)` and let me know if that works for your data. It does work for a test case on my machine with a MULTIPOLYGON layer of ~97000 polygons (while `selfcontained = TRUE` gives the same error as you report above).

**Comment by brry** [comment]
Yes that works, thanks. 
Is it generally not possible to create self-contained html files from large mapviews? 
If so, maybe mapshot could have this as the default setting depending on map size, or mention it in the documentation...

**Comment by tim-salabim** [comment]
Well, at some point it is not advisable anymore to put all data into one html file but rather provide it as a data dependency. Thus, even though the error is actually unrelated to using `selfcontainded = FALSE` setting this does resolve the issue and is the preferred approach. 
Automating this in mapshot is something that is on my plate, but currently not too high on the priority list. I agree though that a note should be added to the documentation. 

Regarding your second issue above, are you referring to the `*_files` folder that does not get deleted together with the html when you only delete the html? If so, you should probably raise that with the **htmlwidget** folk as this is not something that we have under control.

Closing this in assumption that issue is resolved

**Comment by brry** [comment]
Yes it's solved. Thanks so much for all the time you put into mapview!
