### ISSUE TITLE
"sf layer has inconsistent datum" - I humbly disagree

### ISSUE THREAD

**Issue by edzer** [environmentalinformatics-marburg/mapview#72]
I see the following warning:
```r
demo(nc)
> mapview(nc)
Warning message:
sf layer has inconsistent datum (+proj=longlat +datum=NAD27 +no_defs).
Need '+proj=longlat +datum=WGS84' 
```
I don't think that `nc` has an [incosistent datum](https://en.wikipedia.org/wiki/North_American_Datum) but simply a different one from [WGS84](https://en.wikipedia.org/wiki/World_Geodetic_System).

Why not simply use `st_transform` to transform it to WGS84, as you do by other (projected) data sets?

**Comment by tim-salabim** [comment]
This warning come from **leaflet** not mapview. It also happens when we set `native.crs = TRUE`

```r
leaflet() %>% addTiles() %>% addPolygons(data = nc)
mapview(nc, native.crs = TRUE)
```
[In mapview we use `st_is_longlat` to check whether the supplied object is in geographic coordinates](https://github.com/environmentalinformatics-marburg/mapview/blob/develop/R/checkAdjustPorjection.R#L98), which returns `TRUE` in the case of `nc` and thus mapview does not reproject but passes the object straight to the leaflet `add*` methods. 

See this thread for discussion on the projection warning.
https://github.com/rstudio/leaflet/issues/349

**Comment by edzer** [comment]
That is not a sufficient check -- what mapview does is wrong too: mapview will assume WGS84, and that may involve datum transformation, as in this case. If it transforms non-geographic coordinates, so should it transform non-WGS84 datums. [datums 101](https://www.youtube.com/watch?v=xKGlMp__jog). It's a pretty subtle point, but say you're adding 5 lemons to 3 apples, and the software knows, would you like to get a warning, or rather an error?

**Comment by gisma** [comment]
@edzer  I agree  it could help to use consequently the  `st_transform` functionality. Nevertheless I  would like to address  to points:
First, forced transformations will technically  take quite a bit of time for bigger data sets. Second most of the users have NO idea what datum, projected/geographic means. So where to get the correct information for correct transformations? I am not sure how to cover all the weird transformation issues that we will have to deal with. 
So I would suggest to implement a strict error handling if there are any inconsistencies. Even if this will lead to some frustrations.

**Comment by tim-salabim** [comment]
@gisma I think your approach [here](https://github.com/environmentalinformatics-marburg/mapview/blob/master/R/leafletControls.R#L437) is actually what we should use in mapview to make sure we get the correct target crs for the map.

**Comment by edzer** [comment]
It's very odd; you're willing to go from WGS84 to web Mercator (leaflet), or from projected coordinates CRS _y_ to WGS84, all automatic, but not from _known_ datum _x_ to web Mercator (through WGS84). Odd, if not inconsistent.

**Comment by mdsumner** [comment]
Confusion reigns here it would be great to let poor leaflet know what's sensible. Currently they are loathe to reproject at all. Surely CRS-in to desired CRS-out is sufficient to guarantee correct transformation to 4326 for leaflet's internal assumption? Minute details may not be exact but at least the intention wld be right? proj4 R pkg has  source and target args for project() on raw coords, surely an analogous approach is enough?  The current need to be sp or sf objects for general transform takes the hard problem out to users who cannot know. In my experience spTransform is now harmless for identity transformation but that wasn't always the case.

**Comment by tim-salabim** [comment]
I think there are at least two different aspects to address here:

1. technical considereations:
Of course we should (and will) make sure that the target crs we need for leaflet display is correct. We had this implemented in a strict way in the very beginning of mapview but with the recent switch to sf internally this unintentionally became a watered down.
On-the-fly crs transformation is one of the things that differentiates mapview from leaflet and as such provides some convenience to the user. At the same time it is expected from the user to provide data in a valid spatial format (class), i.e. not just a `data.frame` with some x & y columns. @edzer 's example is perfect as it highlights that even if you have valid longlat coordinates in a data.frame they may not be in the exact format that leaflet expects (WGS84 vs. NAD27 in this case). For correct representation it is and should be the responsibility of the user to make sure they know the details of their data. If they do, and provide these details in the form of (correct and complete) crs information, then of course mapview should make sure to convert correctly. 

2. conceptual considerations:
As always with this topic there are broader conceptual considerations to be made. On-the-fly projection is convenient, but somewhat dangerous if the user is not alerted to what is being done to their data in order to display corretly. In the very beginning of mapview we always printed a warning to the console when on-the-fly reprojection was done but that raised a few comments that it is annoying to always see that mesage and additionally it may confuse users that are not used to working with projections etc. Personally, I think we should provide a warning every time we reproject, but am still not sure about the best way to inform the user (via console message). I guess a combination of a useful warning, together with a detailed vignette or similar highlighting the issue may be a way to do this. Suggestions on how to handle this appropriately are more than welcome!

Fianlly, two more points:
1. I don't think that reprojection is much of an overhead, even for large data sets, as my experience is that `st_transform` is very fast and perfomant.
2. I think leaflet should in no way try to re-project on the fly as it is intended to bring leaflet.js to R so it should mirror leaflet.js behaviour. The fact that they opt for a warning in case of non-conformant projection is IMHO desirable but maxy need some more exceptions, especially when using data with no crs and thus no map background (using L.CRS.Simple).

**Comment by gisma** [comment]
Thanks Tim I highly appreciate your outline.

**Comment by edzer** [comment]
The fact that leaflet.js assumes & requires longlat/WGS84 and converts to web Mercator may have to do with GeoJSON [which only allows WGS84](https://tools.ietf.org/html/rfc7946#section-4) and google maps starting with web Mercator, and OSM following (I believe google originally even chose wM because computations on the sphere are much cheaper, and look very similar to those on the ellipsoid).

However, no matter whether this happens in mapview or (R) leaflet, passing data to leaflet.js from which we _know_ they are not in longlat/WGS84 and for which we _know_ how to transform them to longlat/WGS84 is simply the wrong thing to do. The user deserves either automatic conversion or an error, not _knowingly_ misplaced features.

**Comment by hadley** [comment]
2. is a very weak argument: the point is to bring convenient web mapping to R, not a bug-for-bug reimplementation of leaflet.js.

**Comment by tim-salabim** [comment]
e97c7af5dda55784c0a37f62c2de94f44b2e3db0 addresses the issue by cycling through all components of the proj4string of the supplied layer (sf only as of now, raster is still strictly compared via `identical`). If all three components of epsg 4326 are found, no projection is carried out, if not the layer is reprojected and a warning is printed to the console. 
```r
mapview(nc)
Warning message:
In validLongLat(sf::st_crs(x)$proj4string) :
  projection of supplied layer is not leaflet conform.
  projecting to '+proj=longlat +datum=WGS84 +no_defs'
```
because 
```r
mapview(nc)@object
[[1]]
Geometry set for 100 features 
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -84.32377 ymin: 33.88216 xmax: -75.45658 ymax: 36.58977
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
First 5 geometries:
MULTIPOLYGON(((-81.4725791159141 36.23448491106...
MULTIPOLYGON(((-81.2397041640397 36.36549352217...
MULTIPOLYGON(((-80.4561228456383 36.24269680236...
MULTIPOLYGON(((-76.0086191458286 36.31975304003...
MULTIPOLYGON(((-77.2173537793556 36.24113778246...
```
now has a leaflet conform proj4string, while
```
leaflet() %>% addTiles() %>% addPolygons(data = nc)
Warning message:
sf layer has inconsistent datum (+proj=longlat +datum=NAD27 +no_defs).
Need '+proj=longlat +datum=WGS84' 
```
still emits the original warning.

**Comment by edzer** [comment]
Sounds like a complicated task that would be more central to sf, since that can use proj and GDAL?

Anyway, why not simply `st_transform` always anything with `!is.na(st_crs(obj))` to 4326? `sf::st_transform` does nothing if it is already in 4326.

**Comment by tim-salabim** [comment]
does it also do nothing for `"+no_defs +datum=WGS84 +proj=longlat"`? If that is the case, then blindly `st_transforming` would definitely be cleaner

**Comment by edzer** [comment]
That's right.

**Comment by edzer** [comment]
```r
> st_crs("+no_defs +datum=WGS84 +proj=longlat")
$epsg
[1] 4326

$proj4string
[1] "+proj=longlat +datum=WGS84 +no_defs"

attr(,"class")
[1] "crs"
```
so, it "knows" this is EPSG 4326.

**Comment by tim-salabim** [comment]
@hadley point taken, but where would you draw the line? In the end R leaflet provides guessing of coordinate columns in data frames without any projection information.
```r
dframe = data.frame(lng = st_coordinates(nc)[, 1],
                    lat = st_coordinates(nc)[, 2])

leaflet() %>% addTiles() %>% addCircleMarkers(data = dframe)
```
IMHO, if leaflet were to provide on-the-fly reprojection, it would have to take a similar approach to mapview by restricting input to (spatial) objects with useful meta-information.

**Comment by hadley** [comment]
@tim-salabim that problem seems easy to fix - if there's no CRS because the mapping comes from a regular data frame, either force the user to supply a CRS, or assume it's EPSG 4326.

**Comment by gisma** [comment]
The outsourcing of all projections issues to `st_transform` seems to me very efficient. At least we will have the well know  problem cases of gdal and proj4 and can deal with them in a defined and coordinated way.

**Comment by tim-salabim** [comment]
@edzer I like this idea. Simple and effective.

**Comment by tim-salabim** [comment]
@hadley forcing is what mapview does, assuming is what leaflet does. In my opinion that is the way it should be. The only thing that should be implemented is not to print the "Need '+proj=longlat +datum=WGS84' " warning when `L.CRS.Simple` is used, given that we deliberately set this when invoking the map.

**Comment by tim-salabim** [comment]
done. fef0318068abeef5db820eb0769de04e70e29afc

**Comment by mdsumner** [comment]
(This has turned out as I wanted, metadata-in being relied on, ultimately as the user responsibility, and to-target-4326 transforms when needed.  I had some uncertainties that have been collectively resolved here)    Thanks to all!

**Comment by tim-salabim** [comment]
I consider this one closed
